# Site settings
title: rubyist.club
header-img: img/home-bg.jpg
email: chezou@gmail.com
description: "A Podcast by chezou for Rubyist"
baseurl: ""
url: "http://rubyist.club"
twitter_username: chezou
#github_username:  davidtmiller
#facebook_username:  IronSummitMedia

subscribe_rss: http://feeds.rubyist.club/rubyistclub

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","Rakefile","Gemfile"]
