# Site settings
title: rubyist.club
header-img: img/home-bg.jpg
email: chezou@gmail.com
description: "A Podcast by chezou for Rubyist"
baseurl: ""
url: "http://rubyist.club"
twitter_username: chezou
#github_username:  davidtmiller
#facebook_username:  IronSummitMedia

subscribe_rss: http://feeds.rubyist.club/rubyistclub
itunes_url: https://itunes.apple.com/jp/podcast/rubyist.club/id973540950?mt=2

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","Rakefile","Gemfile"]
